---
title: "Project Proposal"
output: pdf_document
date: '2023-11-30'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(knitr)
library(ggplot2)
library(lubridate)


data <- read_csv("data.csv")
# Removing womens fights 
data <- subset(data, !(weight_class %in% c("CatchWeight", "WomenBantamweight", "WomenFeatherweight", "WomenFlyweight", "WomenStrawweight")))
# Filtering out fights where one compeitor has no prior data
#data <- data %>% filter(R_total_rounds_fought != 0 | B_total_rounds_fought != 0)



```

```{r}
data <- data %>% mutate(weight = case_when(weight_class == "Flyweight" ~ 125,
                                   weight_class == "Bantamweight" ~ 135,
                                   weight_class == "Featherweight" ~ 145,
                                   weight_class == "Lightweight" ~ 155,
                                   weight_class == "Welterweight" ~ 170,
                                   weight_class == "Middleweight" ~ 185,
                                   weight_class == "LightHeavyweight" ~ 205, 
                                   weight_class == "Heavyweight" ~ 265, 
                                   weight_class == "OpenWeight" ~ 300))

data <- data %>% mutate(new_class = case_when(weight_class == "Flyweight" ~ "Class 1",
                                   weight_class == "Bantamweight" ~ "Class 1",
                                   weight_class == "Featherweight" ~ "Class 1",
                                   weight_class == "Lightweight" ~ "Class 2",
                                   weight_class == "Welterweight" ~ "Class 2",
                                   weight_class == "Middleweight" ~ "Class 3",
                                   weight_class == "LightHeavyweight" ~ "Class 3", 
                                   weight_class == "Heavyweight" ~ "Class 4", 
                                   weight_class == "OpenWeight" ~ "Class 4"))

freq <- data %>% group_by(new_class, weight_class) %>% 
  summarize(weight = median(weight),
            count = n()) %>% arrange(weight)

kable(freq, caption = "Frequency of Weight Class Fights")


```




```{r}
new_class_freq <- data %>% group_by(new_class) %>% summarize(freq = n())

ggplot(data=new_class_freq, aes(x=new_class, y=freq)) +
  geom_bar(stat="identity", fill="steelblue")+
  theme_minimal() + labs(x = "New Class for Model Building", y = "Count", 
                         title = "Frequency Distribution of New Weight Classes")
```



```{r}
data$date <- as.Date(data$date, format = "%m/%d/%y")

# Extract year from the Date column
data$year <- as.numeric(format(data$date, "%Y"))


year_freq <- data %>% group_by(year) %>% summarize(count = n()) 

ggplot(data = year_freq, mapping = aes(x = year, y = count)) + geom_line() + labs(x = "Year", y = "Number of Fights", title = "Trend of Number of Fights in the UFC")
```

```{r}
data_differences <- data %>% mutate(
  avg_KD_diff = R_avg_KD - B_avg_KD, 
  avg_opp_KD_diff = R_avg_opp_KD - B_avg_opp_KD,
  avg_SIG_STR_pct_diff = R_avg_SIG_STR_pct - B_avg_SIG_STR_pct, 
  avg_TD_pct_diff = R_avg_TD_pct - B_avg_TD_pct, 
  avg_opp_TD_pct_diff = R_avg_opp_TD_pct - B_avg_opp_TD_pct, 
  avg_sub_ATT_diff = R_avg_opp_TD_pct - B_avg_opp_TD_pct, 
  avg_opp_SUB_ATT_diff = R_avg_opp_SUB_ATT - B_avg_opp_SUB_ATT, 
  avg_REV_diff = R_avg_REV - B_avg_REV, 
  avg_opp_REV_diff = R_avg_opp_REV - B_avg_opp_REV, 
  avg_SIG_STR_att_diff = R_avg_SIG_STR_att - B_avg_SIG_STR_att, 
  avg_SIG_STR_landed_diff = R_avg_SIG_STR_landed - B_avg_SIG_STR_landed, 
  avg_opp_SIG_STR_att_diff = R_avg_opp_SIG_STR_att - B_avg_opp_SIG_STR_att, 
  avg_opp_SIG_STR_landed_diff = R_avg_opp_SIG_STR_landed - B_avg_opp_SIG_STR_landed, 
  avg_TOTAL_STR_att_diff = R_avg_TOTAL_STR_att - B_avg_TOTAL_STR_att, 
  avg_TOTAL_STR_landed_diff = R_avg_TOTAL_STR_landed - B_avg_TOTAL_STR_landed, 
  avg_opp_TOTAL_STR_att_diff = R_avg_opp_TOTAL_STR_att - B_avg_opp_TOTAL_STR_att, 
  avg_opp_TOTAL_STR_landed_diff = R_avg_opp_TOTAL_STR_landed - B_avg_opp_TOTAL_STR_landed, 
  avg_TD_att_diff = R_avg_TD_att - B_avg_TD_att,
  avg_TD_landed_diff = R_avg_TD_landed - B_avg_TD_landed, 
  avg_opp_TD_att_diff = R_avg_opp_TD_att - B_avg_opp_TD_att, 
  avg_opp_TD_landed_diff = R_avg_opp_TD_landed - B_avg_opp_TD_landed, 
  avg_HEAD_att_diff = R_avg_HEAD_att - B_avg_HEAD_att, 
  avg_HEAD_landed_diff = R_avg_HEAD_landed - B_avg_HEAD_landed,
  avg_opp_HEAD_att_diff = R_avg_opp_HEAD_att - B_avg_opp_HEAD_att, 
  avg_opp_HEAD_landed_diff = R_avg_opp_HEAD_landed - B_avg_opp_HEAD_landed, 
  avg_BODY_att_diff = R_avg_BODY_att - B_avg_BODY_att, 
  avg_BODY_landed_diff = R_avg_BODY_landed - B_avg_BODY_landed, 
  avg_opp_BODY_att_diff = R_avg_opp_BODY_att - B_avg_opp_BODY_att, 
  avg_opp_BODY_landed_diff = R_avg_opp_BODY_landed - B_avg_opp_BODY_landed, 
  avg_LEG_att_diff = R_avg_LEG_att - B_avg_LEG_att, 
  avg_LEG_landed_diff = R_avg_LEG_landed - B_avg_LEG_landed, 
  avg_opp_LEG_att_diff = R_avg_opp_LEG_att - B_avg_opp_LEG_att, 
  avg_opp_LEG_landed_diff = R_avg_opp_LEG_landed - B_avg_opp_LEG_landed,  
  avg_DISTANCE_att_diff = R_avg_DISTANCE_att - B_avg_DISTANCE_att, 
  avg_DISTANCE_landed_diff = R_avg_DISTANCE_landed - B_avg_DISTANCE_landed, 
  avg_opp_DISTANCE_att_diff = R_avg_opp_DISTANCE_att - B_avg_opp_DISTANCE_att, 
  avg_opp_DISTANCE_landed_diff = R_avg_opp_DISTANCE_landed - B_avg_opp_DISTANCE_landed, 
  avg_CLINCH_att_diff = R_avg_CLINCH_att - B_avg_CLINCH_att, 
  avg_CLINCH_landed_diff = R_avg_CLINCH_landed - B_avg_CLINCH_landed, 
  avg_opp_CLINCH_att_diff = R_avg_opp_CLINCH_att - B_avg_opp_CLINCH_att, 
  avg_opp_CLINCH_landed_diff = R_avg_opp_CLINCH_landed - B_avg_opp_CLINCH_landed, 
  avg_GROUND_att_diff = R_avg_GROUND_att - B_avg_GROUND_att, 
  avg_GROUND_landed_diff = R_avg_GROUND_landed - B_avg_GROUND_landed, 
  avg_opp_GROUND_att_diff = R_avg_opp_GROUND_att - B_avg_opp_GROUND_att, 
  avg_opp_GROUND_landed_diff = R_avg_opp_GROUND_landed - B_avg_opp_GROUND_landed, 
  avg_CTRL_timeseconds_diff = R_avg_CTRL_time_seconds - B_avg_CTRL_time_seconds, 
  avg_opp_CTRL_timeseconds_diff = R_avg_opp_CTRL_time_seconds - B_avg_opp_CTRL_time_seconds, 
  total_time_foughtseconds_diff = R_total_time_fought_seconds - B_total_time_fought_seconds, 
  total_rounds_fought_diff = R_total_rounds_fought - B_total_rounds_fought, 
  total_title_bouts_diff = R_total_title_bouts - B_total_title_bouts, 
  current_win_streak_diff = R_current_win_streak - B_current_win_streak, 
  current_lose_streak_diff = R_current_lose_streak - B_current_lose_streak, 
  longest_win_streak_diff = R_longest_win_streak - B_longest_win_streak, 
  wins_diff = R_wins - B_wins, 
  losses_diff = R_losses - B_losses, 
  draw_diff = R_draw - B_draw, 
  win_by_Decision_Majority_diff = R_win_by_Decision_Majority - B_win_by_Decision_Majority, 
  win_by_Decision_Split_diff = R_win_by_Decision_Split - B_win_by_Decision_Split, 
  win_by_Decision_Unanimous_diff = R_win_by_Decision_Unanimous - B_win_by_Decision_Unanimous, 
  win_by_KO_TKO_diff = R_win_by_KO_TKO - B_win_by_KO_TKO, 
  win_by_Submission_diff = R_win_by_Submission - B_win_by_Submission, 
  win_by_TKO_Doctor_Stoppage_diff = R_win_by_TKO_Doctor_Stoppage - B_win_by_TKO_Doctor_Stoppage, 
  Height_cms_diff = R_Height_cms - B_Height_cms, 
  Reach_cms_diff = R_Reach_cms - B_Reach_cms, 
  Weight_lbs_diff = R_Weight_lbs - B_Weight_lbs)
```


```{r}
# Distribution of number of rounds fought, or a measure experience between the two fighters
ggplot(data = data_differences, mapping = aes(x = total_rounds_fought_diff)) + geom_histogram(binwidth = 5, color = "black", fill = "steelblue") + labs(x = "Total Rounds Fought in Career", title = "Normal Distribution of Difference in Total Rounds between Red and Blue Fighters")
```


```{r}
# Distribution of title fight opportunities between each fighter classification
ggplot(data = data_differences, mapping = aes(x = total_title_bouts_diff)) + geom_histogram(binwidth = 1, color = "black", fill = "steelblue") + labs(x = "Total Title Fights Fought in Career", title = "Normal Distribution of Difference in Total Title Fights between Red and 
Blue Fighters")

```
Those with title fight experience are typically placed in the red corner.

```{r}

datastance_long <- data %>% select(R_Stance, B_Stance) %>% gather(key = "Variable", value = "Value")
ggplot(datastance_long, aes(x = Value, fill = Value)) +
  geom_bar() +
  labs(title = "Frequency of Categories by Group",
       x = "Category",
       y = "Frequency") +
  scale_fill_brewer(palette = "Set3") +  # Change the color palette if needed
  facet_wrap(~ Variable, ncol = 2) +
  theme_minimal() + 

#Exploring potential interaction between stance and attacking attempts
data_differences %>% group_by(R_Stance) %>% 
  summarise(count = n(), mean_sig_shots_connected_pct = sum(R_avg_SIG_STR_landed, na.rm = TRUE)
            /sum(R_avg_SIG_STR_att, na.rm = TRUE), 
            mean_takedown_successes = sum(R_avg_TD_landed, na.rm = TRUE) / sum(R_avg_TD_att, na.rm = TRUE),
            mean_headshots_successes = sum(R_avg_HEAD_landed, na.rm = TRUE) / sum(R_avg_HEAD_att, na.rm = TRUE))

```

```{r}
library(ggplot2)

# Example data frame with categorical and other columns
data <- data.frame(
  Category = factor(rep(c("A", "B", "C"), times = c(20, 30, 50))),
  Group = factor(rep(c("X", "Y"), each = 50))
)

# Creating two separate plots based on the 'Group' column
ggplot(data, aes(x = Category, fill = Category)) +
  geom_bar() +
  labs(title = "Frequency of Categories by Group",
       x = "Category",
       y = "Frequency") +
  scale_fill_brewer(palette = "Set3") +  # Change the color palette if needed
  facet_wrap(~ Group, ncol = 2) +
  theme_minimal()

```


## Random Forest Model Creation 

```{r}
set.seed(2)
class1 <- ufc_data_shuffled_subsetted %>% filter(new_class == "Class 1")
class2 <- ufc_data_shuffled_subsetted %>% filter(new_class == "Class 2")
class3 <- ufc_data_shuffled_subsetted %>% filter(new_class == "Class 3")
class4 <- ufc_data_shuffled_subsetted %>% filter(new_class == "Class 4")

#create ID column
class1$id <- 1:nrow(class1)
#use 70% of dataset as training set and 30% as test set 
class1_train <- class1 %>% dplyr::sample_frac(0.7)
class1_test  <- dplyr::anti_join(class1, class1_train, by = 'id')

#create ID column
class2$id <- 1:nrow(class2)
#use 70% of dataset as training set and 30% as test set 
class2_train <- class2 %>% dplyr::sample_frac(0.7)
class2_test  <- dplyr::anti_join(class2, class2_train, by = 'id')

#create ID column
class3$id <- 1:nrow(class3)
#use 70% of dataset as training set and 30% as test set 
class3_train <- class3 %>% dplyr::sample_frac(0.7)
class3_test  <- dplyr::anti_join(class3, class3_train, by = 'id')

#create ID column
class4$id <- 1:nrow(class4)
#use 70% of dataset as training set and 30% as test set 
class4_train <- class4 %>% dplyr::sample_frac(0.7)
class4_test  <- dplyr::anti_join(class4, class4_train, by = 'id')

```


```{r}
rows_with_na <- class1_train[!complete.cases(class1_train), ]
rf.class1 <- randomForest(Winner~., ntree = 100, data = class1_train)
#yhat.rf <- predict(rf.boston, newdata = Boston[-train,])
rf.class2 <- randomForest(Winner~., ntree = 100, data = class2_train)


class1_train$Winner
```

